#!/bin/sh

TIMESTAMP=$(date +%s)

echo "Creating backups with timesamp: $TIMESTAMP"
cp "$VKB_ROOT_FOLDER"/"$VKB_PROFILE_1" "$VKB_ROOT_FOLDER"/"${TIMESTAMP}_${VKB_PROFILE_1}"
cp "$VKB_ROOT_FOLDER"/"$VKB_PROFILE_2" "$VKB_ROOT_FOLDER"/"${TIMESTAMP}_${VKB_PROFILE_2}"
cp "$X4_ROOT_FOLDER"/"$X4_INPUT_MAP_NAME" "$X4_ROOT_FOLDER"/"$TIMESTAMP"_"$X4_INPUT_MAP_NAME"

cp ./"$VKB_PROFILE_1" "$VKB_ROOT_FOLDER"/"$VKB_PROFILE_1"
cp ./"$VKB_PROFILE_2" "$VKB_ROOT_FOLDER"/"$VKB_PROFILE_2"

cp ./"$X4_INPUT_MAP_FRIENDLY_NAME" "$X4_ROOT_FOLDER"/"$X4_INPUT_MAP_NAME"
